# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$function ssbrc:booth/clone_ridley/animations/animation_model_pose/zzz/frames/$(frame) with storage animated_java:temp entry.data.uuids_by_name
return 1