# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ssbrc:booth/clone_ridley/animations/animation_model_pose/zzz/frames/last_frame_effects with storage animated_java:temp entry.data.uuids_by_name
scoreboard players add @s aj.animation_model_pose.frame 1