# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:booth/clone_ridley rig_hash set value '6aaac54b912baecdc6bc715c4abfac0f12681e8c3bab5256f41e7756113a91b5'
scoreboard objectives add aj.animation_model_pose.frame dummy