# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:booth/clone_ridley"
data modify storage animated_java:temp entry.data.rig_hash set value "6aaac54b912baecdc6bc715c4abfac0f12681e8c3bab5256f41e7756113a91b5"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone5] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone6] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone8] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone9] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone10] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone12] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone15] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone15
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone15 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone14] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone13] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone18] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone18
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone18 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone17] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone17
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone17 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone16] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone16
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone16 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone27] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone27
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone27 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone26] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone26
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone26 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone25] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone25
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone25 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone30] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone30
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone30 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone29] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone29
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone29 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone28] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone28
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone28 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone7] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone4] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone62] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone62
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone62 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone63] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone63
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone63 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone65] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone65
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone65 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone66] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone66
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone66 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone67] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone67
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone67 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone69] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone69
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone69 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone72] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone72
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone72 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone71] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone71
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone71 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone70] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone70
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone70 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone81] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone81
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone81 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone80] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone80
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone80 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone73] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone73
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone73 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone84] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone84
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone84 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone83] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone83
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone83 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone82] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone82
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone82 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone103] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone103
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone103 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone102] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone102
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone102 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone85] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone85
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone85 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone64] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone64
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone64 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone61] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone61
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone61 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone23] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone23
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone23 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone22] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone22
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone22 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone89] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone89
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone89 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone90] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone88] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone88
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone88 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone42] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone42
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone42 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone87] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone87
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone87 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone86] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone86
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone86 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone92] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone92
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone92 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone3] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.head] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.neck] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/neck
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.neck set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone2] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone136] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone136
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone136 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone118] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone118
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone118 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone119] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone119
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone119 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone120] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone120
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone120 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone121] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone121
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone121 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone123] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone123
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone123 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone124] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone124
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone124 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone122] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone122
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone122 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone126] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone126
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone126 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone127] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone127
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone127 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone125] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone125
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone125 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone129] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone129
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone129 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone130] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone130
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone130 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone131] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone131
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone131 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone128] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone128
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone128 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone132] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone132
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone132 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone133] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone133
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone133 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.w5] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/w5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.w2] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/w2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.wing3] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/wing3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone104] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone104
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone104 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone105] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone105
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone105 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone106] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone106
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone106 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone107] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone107
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone107 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone109] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone109
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone109 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone110] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone110
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone110 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone108] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone108
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone108 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone112] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone112
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone112 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone113] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone113
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone113 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone111] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone111
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone111 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone115] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone115
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone115 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone116] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone116
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone116 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone117] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone117
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone117 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone114] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone114
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone114 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone134] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone134
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone134 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone135] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone135
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone135 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.w4] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/w4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.w3] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/w3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.w3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.wing2] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/wing2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.wing2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone20] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone20
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone20 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone101] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone101
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone101 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone100] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone100
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone100 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone99] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone99
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone99 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone98] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone98
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone98 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone97] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone97
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone97 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone96] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone96
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone96 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone95] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone95
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone95 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone94] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone94
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone94 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone93] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone93
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone93 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone24] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone24
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone24 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone32] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone32
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone32 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone36] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone36
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone36 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone35] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone35
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone35 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone34] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone34
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone34 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone77] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone77
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone77 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone75] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone75
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone75 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone39] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone39
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone39 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone76] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone76
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone76 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone74] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone74
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone74 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone40] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone40
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone40 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone79] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone79
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone79 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone78] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone78
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone78 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone41] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone41
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone41 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone38] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone38
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone38 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone33] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone33
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone33 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone31] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone31
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone31 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone19] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone19
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone19 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone44] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone44
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone44 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone46] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone46
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone46 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone50] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone50
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone50 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone49] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone49
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone49 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone48] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone48
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone48 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone54] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone54
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone54 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone53] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone53
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone53 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone52] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone52
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone52 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone57] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone57
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone57 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone56] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone56
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone56 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone55] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone55
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone55 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone60] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone60
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone60 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone59] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone59
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone59 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone58] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone58
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone58 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone51] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone51
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone51 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone47] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone47
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone47 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone45] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone45
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone45 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.clone_ridley.node.bone43] run function ssbrc:booth/clone_ridley/zzz/summon/as_node/bone43
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone43 set from storage animated_java:gu out
function ssbrc:booth/clone_ridley/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:booth/clone_ridley/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:booth/clone_ridley/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 0
execute on passengers run data modify entity @s teleport_duration set value 0
tag @s remove aj.new
execute on passengers run tag @s remove aj.new