# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ssbrc:booth/fighter_select/rig rig_hash set value 'e8119ab45ce50b42147d44de84c74d82541348843c492b5a4c8cb320ac256338'
scoreboard objectives add aj.default.frame dummy
scoreboard objectives add aj.toon_link.frame dummy
scoreboard objectives add aj.roy.frame dummy
scoreboard objectives add aj.fox.frame dummy
scoreboard objectives add aj.lucario.frame dummy
scoreboard objectives add aj.ness.frame dummy
scoreboard objectives add aj.mega_man.frame dummy
scoreboard objectives add aj.hero.frame dummy
scoreboard objectives add aj.peach.frame dummy