# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.default.frame
scoreboard objectives remove aj.toon_link.frame
scoreboard objectives remove aj.roy.frame
scoreboard objectives remove aj.fox.frame
scoreboard objectives remove aj.lucario.frame
scoreboard objectives remove aj.ness.frame
scoreboard objectives remove aj.mega_man.frame
scoreboard objectives remove aj.hero.frame
scoreboard objectives remove aj.peach.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (ssbrc:booth/fighter_select/rig)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'ssbrc:booth/fighter_select/rig',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']