# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ssbrc:booth/fighter_select/rig"
data modify storage animated_java:temp entry.data.rig_hash set value "e8119ab45ce50b42147d44de84c74d82541348843c492b5a4c8cb320ac256338"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.crown] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/crown
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.crown set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.head] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.rwide] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/rwide
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.rwide set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.rslim] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/rslim
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.rslim set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.right_item] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/right_item
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_item set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.right_item2] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/right_item2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_item2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.binding_blade] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/binding_blade
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.binding_blade set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.heros_shield_toon] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/heros_shield_toon
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.heros_shield_toon set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.blaster] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/blaster
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.blaster set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.mr_baseball_bat] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/mr_baseball_bat
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mr_baseball_bat set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.sword_of_light] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/sword_of_light
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.sword_of_light set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.lwide] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/lwide
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.lwide set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.lslim] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/lslim
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.lslim set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.left_item] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/left_item
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_item set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.left_item2] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/left_item2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_item2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.mega_buster] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/mega_buster
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mega_buster set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.master_sword] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/master_sword
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.master_sword set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.heros_shield] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/heros_shield
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.heros_shield set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.body] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.right_leg] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=ssbrc.booth.fighter_select.rig.node.left_leg] run function ssbrc:booth/fighter_select/rig/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
function ssbrc:booth/fighter_select/rig/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function ssbrc:booth/fighter_select/rig/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ssbrc:booth/fighter_select/rig/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 0
execute on passengers run data modify entity @s teleport_duration set value 0
tag @s remove aj.new
execute on passengers run tag @s remove aj.new