# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.default.playing] run function ssbrc:booth/fighter_select/rig/animations/default/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.toon_link.playing] run function ssbrc:booth/fighter_select/rig/animations/toon_link/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.roy.playing] run function ssbrc:booth/fighter_select/rig/animations/roy/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.fox.playing] run function ssbrc:booth/fighter_select/rig/animations/fox/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.lucario.playing] run function ssbrc:booth/fighter_select/rig/animations/lucario/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.ness.playing] run function ssbrc:booth/fighter_select/rig/animations/ness/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.mega_man.playing] run function ssbrc:booth/fighter_select/rig/animations/mega_man/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.hero.playing] run function ssbrc:booth/fighter_select/rig/animations/hero/zzz/on_tick
execute if entity @s[tag=ssbrc.booth.fighter_select.rig.animation.peach.playing] run function ssbrc:booth/fighter_select/rig/animations/peach/zzz/on_tick