# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(crown) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_crown
$execute as $(head) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_head
$execute as $(rwide) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_rwide
$execute as $(rslim) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_rslim
$execute as $(binding_blade) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_binding_blade
$execute as $(heros_shield_toon) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_heros_shield_toon
$execute as $(blaster) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_blaster
$execute as $(mr_baseball_bat) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_mr_baseball_bat
$execute as $(sword_of_light) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_sword_of_light
$execute as $(lwide) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_lwide
$execute as $(lslim) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_lslim
$execute as $(mega_buster) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_mega_buster
$execute as $(master_sword) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_master_sword
$execute as $(heros_shield) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_heros_shield
$execute as $(body) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_body
$execute as $(right_leg) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_right_leg
$execute as $(left_leg) run function ssbrc:booth/fighter_select/rig/variants/hero/zzz/apply_to_node_left_leg