# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.mega_man.frame 0
tag @s add aj.transforms_only
execute at @s run function ssbrc:booth/fighter_select/rig/animations/mega_man/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove ssbrc.booth.fighter_select.rig.animation.mega_man.playing