# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove ssbrc.booth.fighter_select.rig.animation.default.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.toon_link.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.roy.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.fox.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.lucario.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.ness.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.mega_man.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.hero.playing
tag @s remove ssbrc.booth.fighter_select.rig.animation.peach.playing