name: Build Sandstone pack

on:
  push

jobs:
  build_pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v6
        with:
            ref: ${{ github.ref }}
            fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build Pack from TS
        run: |
          bun i
          bun dev:build
          bun dev:deploy

      - name: Upload Resourcepack
        uses: actions/upload-artifact@v4
        with:
          name: ssbrc-latest
          path: |
            .sandstone/output/resourcepack/assets/
            .sandstone/output/resourcepack/pack.mcmeta
            .sandstone/output/resourcepack/pack.png
